name: Build and Deploy .NET Web Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build and publish
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish --configuration Release --output ${{github.workspace}}/publish

    - name: Deploy to AWS Elastic Beanstalk
      env:
        APPLICATION_NAME: "MyWebApp"
        ENVIRONMENT_NAME: "production"
        AWS_DEFAULT_REGION: "eu-west-1"
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws elasticbeanstalk create-application-version --application-name $APPLICATION_NAME --version-label $GITHUB_SHA --source-bundle S3Bucket="$APPLICATION_NAME-$ENVIRONMENT_NAME",S3Key="$GITHUB_SHA.zip"
        aws elasticbeanstalk update-environment --environment-name $ENVIRONMENT_NAME --version-label $GITHUB_SHA
