name: Build and Publish .NET Web Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build and publish
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish --configuration Release --output ${{github.workspace}}/publish

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyWebApp
        path: ${{github.workspace}}/publish
